events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    geo $loggable {
        default 1;
        172.27.0.0/16 0;
    }

    upstream opensearch_backend {
        server os-coord0:9200 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 9200 ssl;
        server_name _;

        ssl_certificate     /run/secrets/public_key;
        ssl_certificate_key /run/secrets/private_key;

        access_log /var/log/nginx/access.log main if=$loggable;

        location / {
            proxy_pass https://opensearch_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }

    upstream opensearch_dashboard {
        server os-dashboard:5601 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 5601;
        server_name _;

        ssl_certificate     /run/secrets/public_key;
        ssl_certificate_key /run/secrets/private_key;

        location / {
            proxy_pass http://opensearch_dashboard;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
