//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nilarea.Generator {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nilarea.Generator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TitleUniquePriority {
            get {
                return ResourceManager.GetString("TitleUniquePriority", resourceCulture);
            }
        }
        
        internal static string MessageFormatUniquePriority {
            get {
                return ResourceManager.GetString("MessageFormatUniquePriority", resourceCulture);
            }
        }
        
        internal static string DescriptionUniquePriority {
            get {
                return ResourceManager.GetString("DescriptionUniquePriority", resourceCulture);
            }
        }
        
        internal static string TitleDuplicateFormat {
            get {
                return ResourceManager.GetString("TitleDuplicateFormat", resourceCulture);
            }
        }
        
        internal static string MessageFormatDuplicateFormat {
            get {
                return ResourceManager.GetString("MessageFormatDuplicateFormat", resourceCulture);
            }
        }
        
        internal static string DescriptionDuplicateFormat {
            get {
                return ResourceManager.GetString("DescriptionDuplicateFormat", resourceCulture);
            }
        }
        
        internal static string TitleInvalidFormat {
            get {
                return ResourceManager.GetString("TitleInvalidFormat", resourceCulture);
            }
        }
        
        internal static string MessageFormatInvalidFormat {
            get {
                return ResourceManager.GetString("MessageFormatInvalidFormat", resourceCulture);
            }
        }
        
        internal static string DescriptionInvalidFormat {
            get {
                return ResourceManager.GetString("DescriptionInvalidFormat", resourceCulture);
            }
        }
        
        internal static string DefaultErrorMessage {
            get {
                return ResourceManager.GetString("DefaultErrorMessage", resourceCulture);
            }
        }
        
        internal static string UseDefaultMessage {
            get {
                return ResourceManager.GetString("UseDefaultMessage", resourceCulture);
            }
        }
        
        internal static string FatalMessage {
            get {
                return ResourceManager.GetString("FatalMessage", resourceCulture);
            }
        }
    }
}
