// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NilArea.Account.Infrastructure.Data;

#nullable disable

namespace NilArea.Account.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20260414053429_InitilizationAccount")]
    partial class InitilizationAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NilArea.Account.Infrastructure.Data.Entities.AccountUser", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordSaltHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK_AccountUser_UserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AccountUser_CreatedAt");

                    b.HasIndex("UpdateAt")
                        .HasDatabaseName("IX_AccountUser_UpdateAt");

                    b.HasIndex("Email", "DeleteAt")
                        .IsUnique()
                        .HasDatabaseName("IX_AccountUser_Email");

                    b.ToTable("AccountUser", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
