using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Resources;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nilarea.Generator;

[Generator]
public class PreEnvironmentValidateGenerator : IIncrementalGenerator
{
    private const string RequireEnvName = "RequireEnvironmentVariableAttribute";
    private const string EnvNameFormatName = "EnvironmentVariableNameFormatAttribute";

    private static readonly ResourceManager ResourceManager = new(typeof(Resources));

    private static readonly LocalizableString DefaultErrorMessage =
        new LocalizableResourceString(nameof(DefaultErrorMessage), ResourceManager, typeof(Resources));

    private static readonly LocalizableString UseDefaultMessage =
        new LocalizableResourceString(nameof(UseDefaultMessage), ResourceManager, typeof(Resources));

    private static readonly LocalizableString FatalMessage =
        new LocalizableResourceString(nameof(FatalMessage), ResourceManager, typeof(Resources));

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 收集所有包含 RequireEnvironmentVariableAttribute 的语法节点
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => IsCandidateNode(node),
                static (ctx, ct) => GetEnvironmentValidate(ctx, ct).Where(e => e is not null).ToList())
            .Where(static m => m is not null)
            .Collect();

        context.RegisterSourceOutput(provider, GenerateValidationCode);
    }

    private static void GenerateValidationCode(SourceProductionContext context,
        ImmutableArray<List<EnvironmentValidateSyntax?>> members)
    {
        var validMembers = members.SelectMany(a => a.Where(t => t is not null)).Select(t => t!).ToArray();
        if (!validMembers.Any()) return;
        var sw = new StringWriter();
        using var writer = new IndentedTextWriter(sw, "    ");
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#nullable enable");
        writer.WriteLine(
            "[assembly: System.CodeDom.Compiler.GeneratedCode(\"PreEnvironmentValidateGenerator\", \"1.0.0\")]");
        writer.WriteLine("");
        writer.WriteLine("[System.CodeDom.Compiler.GeneratedCode(\"PreEnvironmentValidateGenerator\", \"1.0.0\")]");
        writer.WriteLine("[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        writer.WriteLine("internal static partial class NilareaGenerator");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("[System.Runtime.CompilerServices.ModuleInitializer]");
        writer.WriteLine("public static void ValidateEnvironmentVariables()");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("bool valid = true;");
        foreach (var member in validMembers)
            GenerateSingleCheck(writer, member);
        writer.WriteLine("if (!valid)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"System.Console.WriteLine(\"{FatalMessage.ToString()}\");");
        writer.WriteLine("Environment.Exit(1);");
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
        context.AddSource("EnvironmentValidator.g.cs", SourceText.From(sw.ToString(), Encoding.UTF8));
    }

    private static void GenerateSingleCheck(
        IndentedTextWriter writer,
        EnvironmentValidateSyntax? syntax)
    {
        if (syntax is null) return;
        var member = (EnvironmentValidateSyntax)syntax;
        var envName = member.Attribute.ConstructorArguments[0].Value;
        string? envErrorMessage = null;
        string? envDefaultValue = null;
        var envFailFast = true;
        foreach (var named in member.Attribute.NamedArguments)
        {
            if (named is { Key: "ErrorMessage", Value.Value: string errorMessage })
                envErrorMessage = errorMessage;
            if (named is { Key: "DefaultValue", Value.Value: string defaultValue })
                envDefaultValue = defaultValue;
            if (named is { Key: "FailFast", Value.Value: bool failFast })
                envFailFast = failFast;
        }

        envErrorMessage ??= string.Format(DefaultErrorMessage.ToString(), envName);
        writer.WriteLine($"if (System.Environment.GetEnvironmentVariable(\"{envName}\") is null)");
        writer.WriteLine("{");
        writer.Indent++;
        if (member.Formats.Count is 0)
        {
            if (string.IsNullOrWhiteSpace(envDefaultValue))
            {
                if (envFailFast)
                    writer.WriteLine("valid = false;");
                writer.WriteLine($"Console.Error.WriteLine(\"{envErrorMessage}\");");
            }
            else
            {
                writer.WriteLine($"System.Environment.SetEnvironmentVariable(\"{envName}\", \"{envDefaultValue}\");");
                writer.WriteLine(
                    $"Console.Error.WriteLine(\"{string.Format(UseDefaultMessage.ToString(), envName, envDefaultValue)}\");");
            }
        }
        else
        {
            writer.WriteLine("bool match = false;");
            List<(int Priority, string ExEnvName)> formats = [];
            foreach (var attr in member.Formats)
            {
                var priority = 0;
                string? prefix = null;
                string? suffix = null;
                foreach (var named in attr.NamedArguments)
                {
                    if (named is { Key: "Priority", Value.Value: int priorityValue })
                        priority = priorityValue;
                    if (named is { Key: "Prefix", Value.Value: string prefixValue })
                        prefix = prefixValue;
                    if (named is { Key: "Suffix", Value.Value: string suffixValue })
                        suffix = suffixValue;
                }

                string exName;
                if (string.IsNullOrWhiteSpace(prefix))
                    exName = $"{envName}{suffix}";
                else if (string.IsNullOrWhiteSpace(suffix))
                    exName = $"{prefix}{envName}";
                else
                    exName = $"{prefix}{envName}{suffix}";
                formats.Add((priority, exName));
            }

            formats.Sort(static (l, r) => l.Priority.CompareTo(r.Priority));
            foreach (var (_, name) in formats)
            {
                writer.WriteLine($"if (System.Environment.GetEnvironmentVariable(\"{name}\") is not null)");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine("match = true;");
                writer.Indent--;
                writer.WriteLine("}");
            }

            writer.WriteLine("if (!match)");
            writer.WriteLine("{");
            writer.Indent++;
            if (string.IsNullOrWhiteSpace(envDefaultValue))
            {
                if (envFailFast)
                    writer.WriteLine("valid = false;");
                writer.WriteLine($"Console.Error.WriteLine(\"{envErrorMessage}\");");
            }
            else
            {
                writer.WriteLine($"System.Environment.SetEnvironmentVariable(\"{envName}\", \"{envDefaultValue}\");");
                writer.WriteLine(
                    $"Console.Error.WriteLine(\"{string.Format(UseDefaultMessage.ToString(), envName, envDefaultValue)}\");");
            }

            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Indent--;
        writer.WriteLine("}");
    }

    private static bool IsCandidateNode(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax
            or StructDeclarationSyntax
            or FieldDeclarationSyntax
            or PropertyDeclarationSyntax
            or MethodDeclarationSyntax
            or ParameterSyntax
            or LocalFunctionStatementSyntax;
    }

    private static IEnumerable<EnvironmentValidateSyntax?> GetEnvironmentValidate(GeneratorSyntaxContext ctx,
        CancellationToken ct)
    {
        var semanticModel = ctx.SemanticModel;
        switch (ctx.Node)
        {
            case ClassDeclarationSyntax @class:
            {
                if (semanticModel.GetDeclaredSymbol(@class, ct) is not INamedTypeSymbol symbol)
                    yield break;
                var attrs = GetRequireEnvAttributes(symbol, semanticModel, ct);
                if (attrs.Count == 0) yield break;
                var formats = GetEnvNameFormatAttributes(symbol, semanticModel, ct);
                foreach (var attr in attrs)
                    yield return new EnvironmentValidateSyntax(attr, formats);
                break;
            }
            case StructDeclarationSyntax @struct:
            {
                if (semanticModel.GetDeclaredSymbol(@struct, ct) is not INamedTypeSymbol symbol)
                    yield break;
                var attrs = GetRequireEnvAttributes(symbol, semanticModel, ct);
                if (attrs.Count == 0) yield break;
                var formats = GetEnvNameFormatAttributes(symbol, semanticModel, ct);
                foreach (var attr in attrs)
                    yield return new EnvironmentValidateSyntax(attr, formats);
                break;
            }
            case FieldDeclarationSyntax fields:
            {
                foreach (var field in fields.Declaration.Variables)
                {
                    if (semanticModel.GetDeclaredSymbol(field, ct) is not IFieldSymbol symbol)
                        continue;
                    var attrs = GetRequireEnvAttributes(symbol, semanticModel, ct);
                    if (attrs.Count == 0) continue;
                    var fieldFormats = GetEnvNameFormatAttributes(symbol, semanticModel, ct);
                    var typeFormats = GetEnvNameFormatAttributes(symbol.ContainingType, semanticModel, ct);
                    var allFormats = typeFormats.Concat(fieldFormats).ToList();
                    foreach (var attr in attrs)
                        yield return new EnvironmentValidateSyntax(attr, allFormats);
                }

                break;
            }
            case PropertyDeclarationSyntax property:
            {
                if (semanticModel.GetDeclaredSymbol(property, ct) is not IPropertySymbol symbol)
                    yield break;
                var attrs = GetRequireEnvAttributes(symbol, semanticModel, ct);
                if (attrs.Count == 0) yield break;
                var propertyFormats = GetEnvNameFormatAttributes(symbol, semanticModel, ct);
                var typeFormats = GetEnvNameFormatAttributes(symbol.ContainingType, semanticModel, ct);
                var allFormats = typeFormats.Concat(propertyFormats).ToList();
                foreach (var attr in attrs)
                    yield return new EnvironmentValidateSyntax(attr, allFormats);
                break;
            }
            case MethodDeclarationSyntax method:
            {
                if (semanticModel.GetDeclaredSymbol(method, ct) is not IMethodSymbol symbol)
                    yield break;
                var attrs = GetRequireEnvAttributes(symbol, semanticModel, ct);
                if (attrs.Count == 0) yield break;
                var methodFormats = GetEnvNameFormatAttributes(symbol, semanticModel, ct);
                var typeFormats = GetEnvNameFormatAttributes(symbol.ContainingType, semanticModel, ct);
                var allFormats = typeFormats.Concat(methodFormats).ToList();
                foreach (var attr in attrs)
                    yield return new EnvironmentValidateSyntax(attr, allFormats);
                break;
            }
            case LocalFunctionStatementSyntax local:
            {
                if (semanticModel.GetDeclaredSymbol(local, ct) is not IMethodSymbol symbol)
                    yield break;
                var attrs = GetRequireEnvAttributes(symbol, semanticModel, ct);
                if (attrs.Count == 0) yield break;
                var methodFormats = GetEnvNameFormatAttributes(symbol, semanticModel, ct);
                var typeFormats = GetEnvNameFormatAttributes(symbol.ContainingType, semanticModel, ct);
                var allFormats = typeFormats.Concat(methodFormats).ToList();
                foreach (var attr in attrs)
                    yield return new EnvironmentValidateSyntax(attr, allFormats);
                break;
            }
            case ParameterSyntax param:
            {
                if (semanticModel.GetDeclaredSymbol(param, ct) is not IParameterSymbol symbol)
                    yield break;
                var attrs = GetRequireEnvAttributes(symbol, semanticModel, ct);
                if (attrs.Count == 0) yield break;
                var paramFormats = GetEnvNameFormatAttributes(symbol, semanticModel, ct);
                List<AttributeData> allFormats;
                if (symbol.ContainingSymbol is IMethodSymbol)
                {
                    var methodFormats = GetEnvNameFormatAttributes(symbol.ContainingSymbol, semanticModel, ct);
                    var typeFormats = GetEnvNameFormatAttributes(symbol.ContainingType, semanticModel, ct);
                    allFormats = typeFormats.Concat(methodFormats).Concat(paramFormats).ToList();
                }
                else
                {
                    var typeFormats = GetEnvNameFormatAttributes(symbol.ContainingType, semanticModel, ct);
                    allFormats = typeFormats.Concat(paramFormats).ToList();
                }

                foreach (var attr in attrs)
                    yield return new EnvironmentValidateSyntax(attr, allFormats);
                break;
            }
        }
    }

    private static List<AttributeData> GetRequireEnvAttributes(ISymbol symbol, SemanticModel model,
        CancellationToken ct)
    {
        if (symbol is ITypeSymbol { TypeKind: TypeKind.Extension })
            symbol = symbol.ContainingType;
        return symbol.GetAttributes()
            .Where(static attr => attr.AttributeClass?.ToDisplayString().Contains(RequireEnvName) ?? false)
            .Where(a => a is not null)
            .Select(a => a!)
            .ToList();
    }

    private static List<AttributeData> GetEnvNameFormatAttributes(ISymbol symbol, SemanticModel model,
        CancellationToken ct)
    {
        if (symbol is ITypeSymbol { TypeKind: TypeKind.Extension })
            symbol = symbol.ContainingType;
        return symbol.GetAttributes()
            .Where(static attr => attr.AttributeClass?.ToDisplayString().Contains(EnvNameFormatName) ?? false)
            .Where(a => a is not null)
            .Select(a => a!)
            .ToList();
    }

    private readonly record struct EnvironmentValidateSyntax(
        AttributeData Attribute,
        List<AttributeData> Formats)
    {
        public AttributeData Attribute { get; } = Attribute;
        public List<AttributeData> Formats { get; } = Formats;
    }
}