name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
        working-directory: frontend/webapp
      - uses: actions/setup-node@v4
        with:
          node-version: "v22.22.1"
      - run: npm install
        working-directory: frontend/webapp
      - run: NUXT_APP_BASE_URL=/${{ github.event.repository.name }}/ npx nuxt build --preset github_pages
        working-directory: frontend/webapp
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/webapp/.output/public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4